---
- name: Install Docker 
  hosts: appnodes
  tasks:
  - name: Install required packages
    yum: 
      name:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      state: present
      update_cache: yes
    become: True

  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    become: True

  - name: Install Docker CE
    yum:
      name:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
      state: present
      update_cache: yes
    become: True

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes
    become: True

  - name: Add user to docker group
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes
    become: True
