---
- name: Test
  become: yes
  hosts: openstack
  gather_facts: no

  tasks:

    - name: Create internal network
      os_network:
        state: present
        auth:
          auth_url: http://controller:5000/v3
          username: admin
          password: mda33ncedu
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
        name: int_net
        provider_network_type: vxlan
        shared: yes

    - name: Create management network
      os_network:
        state: present
        auth:
          auth_url: http://controller:5000/v3
          username: admin
          password: mda33ncedu
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
        name: mgmt_net
        interface: admin
        provider_network_type: vxlan
        shared: no

    - name: Create a subnet for int_net
      os_subnet:
        state: present
        auth:
          auth_url: http://controller:5000/v3
          username: admin
          password: mda33ncedu
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
        network_name: int_net
        name: int_subnet
        cidr: 192.168.0.0/24
        gateway_ip: 192.168.0.1
        enable_dhcp: yes
        allocation_pool_start: 192.168.0.100
        allocation_pool_end: 192.168.0.200

    - name: Create subnet for a management network
      os_subnet:
        state: present
        auth:
          auth_url: http://controller:5000/v3
          username: admin
          password: mda33ncedu
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
        network_name: mgmt_net
        name: mgmt_subnet
        cidr: 192.168.100.0/24
        gateway_ip: 192.168.100.1
        enable_dhcp: yes
        allocation_pool_start: 192.168.100.100
        allocation_pool_end: 192.168.100.200

    - name: Create router
      os_router:
        state: present
        auth:
          auth_url: http://controller:5000/v3
          username: admin
          password: mda33ncedu
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
        name: router01
        enable_snat: yes
        network: ext_net
        external_fixed_ips:
          - subnet: ext_subnet
            ip: 172.16.15.254
        interfaces:
          - mgmt_subnet

    - name: Create server1 instance
      register: server1_vm
      os_server:
        state: present
        auth:
          auth_url: http://controller:5000/v3
          username: admin
          password: mda33ncedu
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
        name: server1
        flavor: b9befdb5-84fb-45f4-ac79-6e51ff1d8da2
        image: cf1a422b-e398-451a-ab7a-5c23f2e201f8
        security_groups:
          - default
          - secgroup01
        key_name: centos_key
        nics:
          - net-id: d596bab6-7d17-4557-b2f8-8c4a4cfb637b
          - net-name: int_net
    
    - name: Add server1 to group 'instances'
      add_host:
        name: "{{ server1_vm.openstack.addresses.ext_net[0].addr }}" 
        groups: instances

    - name: Create server2 instance
      register: server2_vm
      os_server:
        state: present
        auth:
          auth_url: http://controller:5000/v3
          username: admin
          password: mda33ncedu
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
        name: server2
        flavor: b9befdb5-84fb-45f4-ac79-6e51ff1d8da2
        image: cf1a422b-e398-451a-ab7a-5c23f2e201f8
        security_groups:
          - default
          - secgroup01
        key_name: centos_key
        nics:
          - net-name: mgmt_net
          - net-name: int_net
        auto_ip: no

    - name: Cerate server3 instance
      register: server3_vm
      os_server:
        state: present
        auth:
          auth_url: http://controller:5000/v3
          username: admin
          password: mda33ncedu
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
        name: server3
        flavor: b9befdb5-84fb-45f4-ac79-6e51ff1d8da2
        image: cf1a422b-e398-451a-ab7a-5c23f2e201f8
        security_groups:
          - default
          - secgroup01
        key_name: centos_key
        nics:
          - net-name: mgmt_net
          - net-name: int_net
        auto_ip: no

    - name: Creating floating ip
      register: f_ip_2
      os_floating_ip:
        state: present
        auth:
          auth_url: http://controller:5000/v3
          username: admin
          password: mda33ncedu
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
        network: ext_net
        nat_destination: mgmt_net
        server: server2
      
    - name: Add server2 to group 'instances'
      add_host:
        name: "{{ f_ip_2.floating_ip.floating_ip_address }}" 
        groups: instances

    - name: Creating floating ip
      register: f_ip_3
      os_floating_ip:
        state: present
        auth:
          auth_url: http://controller:5000/v3
          username: admin
          password: mda33ncedu
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
        network: ext_net
        nat_destination: mgmt_net
        server: server3

    - name: Add server3 to group 'instances'
      add_host:
        name: "{{ f_ip_3.floating_ip.floating_ip_address }}" 
        groups: instances

    - name: Create inventory file for instances
      become: no  
      template:
        src: ansible-hosts.j2
        dest: inventory_instances
      delegate_to: 127.0.0.1

...
