---
# tasks file for mariadb
- name: "Create /home/{{ ansible_user }}/compose dir if not exists"
  file: 
    path: "/home/{{ ansible_user }}/compose"
    state: directory
  

- name: Template a db-compose file 
  template:
    src: db-compose.j2
    dest: "/home/{{ ansible_user }}/compose/db-compose.yml"

- name: Deploy database sevice to docker swarm
  docker_stack:
    state: present
    name: "{{ docker_stack_name }}" 
    compose:
      - "/home/{{ ansible_user }}/compose/db-compose.yml"

