- name: Pull an image
  docker_image:
    name: clue/ttrss 
    source: pull

- name: Create and start a container
  docker_container:
    name: ttrss_app
    image: clue/ttrss
    state: started
    published_ports: "{{ ttrss_host_ip_addr }}:{{ ttrss_port }}:80"
    env: 
      DB_HOST: "{{ db_host_ip_addr }}"
      DB_PORT: "{{ db_port }}"
      DB_NAME: "{{ db_ttrss_dbname }}"
      DB_USER: "{{ db_ttrss_user }}"
      DB_PASS: "{{ db_ttrss_pass }}"
      DB_TYPE: "{{ db_type }}"

- name: Container present
  docker_container:
    name: ttrss_app 
    state: present
    image: clue/ttrss 
